import type { ComponentType } from "react";
import {
  TypoSizeOnlyHierarchy,
  TypoMultiDimensionHierarchy,
  TypoLongLines,
  TypoOptimalWidth,
  TypoTightLeading,
  TypoRelaxedLeading,
  TypoNoScale,
  TypoHarmonicScale,
} from "./typography";
import {
  SpacingRandom,
  SpacingConsistentScale,
  SpacingCramped,
  SpacingGenerous,
  SpacingNoProximity,
  SpacingProximity,
  SpacingBorderSeparation,
  SpacingWhitespaceSeparation,
} from "./spacing";
import {
  ColorLowContrast,
  ColorAccessibleContrast,
  ColorTooManyColors,
  ColorLimitedPalette,
  ColorGreyOnColor,
  ColorTintedOnColor,
  ColorPureBlackOnWhite,
  ColorSoftContrast,
} from "./color";
import {
  HierarchyFlat,
  HierarchyClear,
  ButtonsAllPrimary,
  ButtonsWithHierarchy,
  EverythingBold,
  SelectiveEmphasis,
  LabelSameAsValue,
  LabelDimmedValueBold,
} from "./hierarchy";
import {
  LayoutFullWidth,
  LayoutConstrained,
  FormSideBySide,
  FormStacked,
  CardLayoutUneven,
  CardLayoutConsistent,
  ContentLeftAligned,
  ContentCenterAligned,
} from "./layout";
import {
  FormPlaceholderLabels,
  FormVisibleLabels,
  FormGenericError,
  FormSpecificError,
  FormTinyTargets,
  FormLargeTargets,
  FormWallOfFields,
  FormGroupedFields,
} from "./forms";
import {
  FeedbackBlankLoading,
  FeedbackSkeleton,
  FeedbackEmptyBare,
  FeedbackEmptyHelpful,
  FeedbackTechnicalError,
  FeedbackFriendlyError,
  FeedbackNoConfirmation,
  FeedbackConfirmation,
} from "./feedback";
import {
  NavVagueLabels,
  NavSpecificLabels,
  NavNoBreadcrumbs,
  NavBreadcrumbs,
  NavDeepNesting,
  NavMegaMenu,
  NavMobileSqueezed,
  NavMobileHamburger,
} from "./navigation";
import {
  A11yNoFocusRing,
  A11yVisibleFocusRing,
  A11yIconOnly,
  A11yIconWithLabel,
  A11yColorOnlyStatus,
  A11yRichStatus,
  A11yColorOnlyLinks,
  A11yUnderlinedLinks,
} from "./accessibility";
import {
  MicroNoButtonFeedback,
  MicroButtonWithFeedback,
  MicroInstantToggle,
  MicroAnimatedToggle,
  MicroAbruptEntrance,
  MicroStaggeredEntrance,
  MicroIndeterminateProgress,
  MicroStepProgress,
} from "./micro-interactions";
import {
  CopyTechnicalError,
  CopyFriendlyError,
  CopyWallOfText,
  CopyScannableContent,
  CopyGenericLinks,
  CopyDescriptiveLinks,
  CopyJargonOnboarding,
  CopyPlainOnboarding,
} from "./content-copy";
import {
  DataLeftAlignedNumbers,
  DataRightAlignedNumbers,
  DataTextCutOff,
  DataEllipsisWithTooltip,
  DataDenseTable,
  DataPrioritizedTable,
  DataEmptyBare,
  DataEmptyHelpful,
} from "./data-display";
import {
  ModalFullScreenConfirm,
  ModalInlineConfirm,
  ModalNoDismiss,
  ModalMultipleDismiss,
  ModalOverloadedForm,
  ModalMultiStepFlow,
  ModalPopupOverload,
  ModalCleanFirstVisit,
} from "./modals-overlays";
import {
  CardUnevenHeights,
  CardUniformHeights,
  CardNoAffordance,
  CardWithAffordance,
  CardOverloaded,
  CardFocused,
  ListFlat,
  ListGrouped,
} from "./lists-cards";
import {
  IconMixedStyles,
  IconConsistentStyles,
  IconGenericHero,
  IconMeaningfulHero,
  IconAmbiguous,
  IconRecognized,
  IconPoorImageQuality,
  IconProperImageQuality,
} from "./icons-imagery";

/** Maps componentId strings to their React components. */
export const visualRegistry: Record<string, ComponentType> = {
  // Typography
  TypoSizeOnlyHierarchy,
  TypoMultiDimensionHierarchy,
  TypoLongLines,
  TypoOptimalWidth,
  TypoTightLeading,
  TypoRelaxedLeading,
  TypoNoScale,
  TypoHarmonicScale,
  // Spacing
  SpacingRandom,
  SpacingConsistentScale,
  SpacingCramped,
  SpacingGenerous,
  SpacingNoProximity,
  SpacingProximity,
  SpacingBorderSeparation,
  SpacingWhitespaceSeparation,
  // Color
  ColorLowContrast,
  ColorAccessibleContrast,
  ColorTooManyColors,
  ColorLimitedPalette,
  ColorGreyOnColor,
  ColorTintedOnColor,
  ColorPureBlackOnWhite,
  ColorSoftContrast,
  // Hierarchy
  HierarchyFlat,
  HierarchyClear,
  ButtonsAllPrimary,
  ButtonsWithHierarchy,
  EverythingBold,
  SelectiveEmphasis,
  LabelSameAsValue,
  LabelDimmedValueBold,
  // Layout
  LayoutFullWidth,
  LayoutConstrained,
  FormSideBySide,
  FormStacked,
  CardLayoutUneven,
  CardLayoutConsistent,
  ContentLeftAligned,
  ContentCenterAligned,
  // Forms
  FormPlaceholderLabels,
  FormVisibleLabels,
  FormGenericError,
  FormSpecificError,
  FormTinyTargets,
  FormLargeTargets,
  FormWallOfFields,
  FormGroupedFields,
  // Feedback
  FeedbackBlankLoading,
  FeedbackSkeleton,
  FeedbackEmptyBare,
  FeedbackEmptyHelpful,
  FeedbackTechnicalError,
  FeedbackFriendlyError,
  FeedbackNoConfirmation,
  FeedbackConfirmation,
  // Navigation
  NavVagueLabels,
  NavSpecificLabels,
  NavNoBreadcrumbs,
  NavBreadcrumbs,
  NavDeepNesting,
  NavMegaMenu,
  NavMobileSqueezed,
  NavMobileHamburger,
  // Accessibility
  A11yNoFocusRing,
  A11yVisibleFocusRing,
  A11yIconOnly,
  A11yIconWithLabel,
  A11yColorOnlyStatus,
  A11yRichStatus,
  A11yColorOnlyLinks,
  A11yUnderlinedLinks,
  // Micro-interactions
  MicroNoButtonFeedback,
  MicroButtonWithFeedback,
  MicroInstantToggle,
  MicroAnimatedToggle,
  MicroAbruptEntrance,
  MicroStaggeredEntrance,
  MicroIndeterminateProgress,
  MicroStepProgress,
  // Content & Copy
  CopyTechnicalError,
  CopyFriendlyError,
  CopyWallOfText,
  CopyScannableContent,
  CopyGenericLinks,
  CopyDescriptiveLinks,
  CopyJargonOnboarding,
  CopyPlainOnboarding,
  // Data Display
  DataLeftAlignedNumbers,
  DataRightAlignedNumbers,
  DataTextCutOff,
  DataEllipsisWithTooltip,
  DataDenseTable,
  DataPrioritizedTable,
  DataEmptyBare,
  DataEmptyHelpful,
  // Modals & Overlays
  ModalFullScreenConfirm,
  ModalInlineConfirm,
  ModalNoDismiss,
  ModalMultipleDismiss,
  ModalOverloadedForm,
  ModalMultiStepFlow,
  ModalPopupOverload,
  ModalCleanFirstVisit,
  // Lists & Cards
  CardUnevenHeights,
  CardUniformHeights,
  CardNoAffordance,
  CardWithAffordance,
  CardOverloaded,
  CardFocused,
  ListFlat,
  ListGrouped,
  // Icons & Imagery
  IconMixedStyles,
  IconConsistentStyles,
  IconGenericHero,
  IconMeaningfulHero,
  IconAmbiguous,
  IconRecognized,
  IconPoorImageQuality,
  IconProperImageQuality,
};
