import type { BaseChallenge } from "../../game/types";

export const largeFilesChallenges: BaseChallenge[] = [
  {
    id: "lf-001",
    category: "large-files",
    difficulty: "easy",
    title: "Tracking binary assets",
    prompt: "Which approach handles large binary files in a Git repo?",
    content: {
      type: "code",
      lang: "bash",

      left: `# Track large files with Git LFS
git lfs install
git lfs track "*.psd"
git lfs track "*.zip"
git add .gitattributes
git add assets/design.psd
git commit -m "Add design file via LFS"`,

      right: `# Just commit the files directly
git add assets/design.psd
git add assets/archive.zip
git commit -m "Add design file"
# It's only 200 MB, should be fine`,
    },

    correctSide: "left",
    explanationCorrect:
      "Git LFS (Large File Storage) replaces large files with lightweight pointer files in the repo, while storing the actual file contents on a remote server. This keeps the repo small and fast to clone. Without LFS, every clone downloads the full history of every binary file.",
    explanationWrong:
      "Committing large binaries directly into Git is one of the most common mistakes. Git stores every version of every file, so a 200 MB PSD that changes 10 times adds 2 GB to the repo history. This cannot be easily undone and makes cloning slow for every contributor.",
    sourceUrl: "https://git-lfs.com/",
    sourceLabel: "Git LFS: Large File Storage",
  },
  {
    id: "lf-002",
    category: "large-files",
    difficulty: "easy",
    title: "LFS tracking configuration",
    prompt: "Which .gitattributes setup for LFS is more thorough?",
    content: {
      type: "code",

      left: `# .gitattributes
*.png filter=lfs diff=lfs
  merge=lfs -text
*.jpg filter=lfs diff=lfs
  merge=lfs -text
*.gif filter=lfs diff=lfs
  merge=lfs -text
*.psd filter=lfs diff=lfs
  merge=lfs -text
*.zip filter=lfs diff=lfs
  merge=lfs -text
*.woff2 filter=lfs diff=lfs
  merge=lfs -text`,

      right: `# .gitattributes
*.psd filter=lfs diff=lfs
  merge=lfs -text
*.zip filter=lfs diff=lfs
  merge=lfs -text`,
    },

    correctSide: "left",
    explanationCorrect:
      "Tracking all binary file types with LFS from the start prevents accidental commits of untracked binaries. Images (PNG, JPG, GIF), design files (PSD), archives (ZIP), and fonts (WOFF2) are all binary formats that should go through LFS. It is much easier to set this up early than to migrate files later.",
    explanationWrong:
      "Only tracking a few file types leaves gaps. When a developer adds a PNG or WOFF2 font, it goes straight into Git history. Once a large binary is committed without LFS, removing it requires history rewriting with tools like BFG Repo Cleaner. Be proactive and track all known binary types.",
    sourceUrl:
      "https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage",
    sourceLabel: "GitHub Docs: Configuring Git LFS",
  },
  {
    id: "lf-003",
    category: "large-files",
    difficulty: "medium",
    title: "Compiled assets in the repo",
    prompt: "Which approach to compiled/built assets is correct?",
    content: {
      type: "code",

      left: `# .gitignore
dist/
build/
.next/
out/

# CI builds from source
# npm run build`,

      right: `# Commit built files so deploys
# don't need a build step
# dist/ is checked in

git add dist/
git commit -m "Update build output"`,
    },

    correctSide: "left",
    explanationCorrect:
      "Build output should be generated by CI/CD pipelines, not committed to the repo. Committing compiled assets causes constant merge conflicts, bloats the repo, and creates a risk of the source and build getting out of sync. Let your CI system build from source every time.",
    explanationWrong:
      "Checking in build output seems convenient but causes real problems. Every code change creates a second diff in the compiled files. Merge conflicts in minified bundles are nearly impossible to resolve. The build output can also drift from the source if someone forgets to rebuild before committing.",
    sourceUrl:
      "https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files",
    sourceLabel: "GitHub Docs: Ignoring files",
  },
  {
    id: "lf-004",
    category: "large-files",
    difficulty: "medium",
    title: "Cleaning up repo history",
    prompt:
      "Which tool is recommended for removing large files from Git history?",
    content: {
      type: "code",
      lang: "bash",

      left: `# BFG Repo-Cleaner
# Fast, simple, purpose-built

# Remove files over 100 MB
java -jar bfg.jar \
  --strip-blobs-bigger-than 100M \
  my-repo.git

# Remove specific file from history
java -jar bfg.jar \
  --delete-files database.sql \
  my-repo.git

git reflog expire --expire=now --all
git gc --prune=now --aggressive`,

      right: `# git filter-branch
# Built-in but slow and error-prone

git filter-branch \
  --force --index-filter \
  'git rm --cached \
  --ignore-unmatch database.sql' \
  --prune-empty \
  --tag-name-filter cat \
  -- --all

git reflog expire --expire=now --all
git gc --prune=now --aggressive`,
    },

    correctSide: "left",
    explanationCorrect:
      "BFG Repo-Cleaner is 10 to 720 times faster than git filter-branch and has a much simpler interface. It is specifically designed for removing large files and sensitive data from Git history. Even the official Git documentation recommends using alternatives to filter-branch.",
    explanationWrong:
      "While `git filter-branch` is built into Git, it is slow, complex, and officially deprecated in favor of better tools. The Git docs themselves warn against using it and suggest `git filter-repo` or BFG instead. The syntax is error-prone and a single mistake can corrupt your history.",
    sourceUrl: "https://rtyley.github.io/bfg-repo-cleaner/",
    sourceLabel: "BFG Repo-Cleaner",
  },
  {
    id: "lf-005",
    category: "large-files",
    difficulty: "hard",
    title: "Cloning large repositories",
    prompt: "Which cloning strategy is better for large repos in CI?",
    content: {
      type: "code",
      lang: "bash",

      left: `# Shallow clone with single branch
git clone \
  --depth 1 \
  --single-branch \
  --branch main \
  https://github.com/org/large-repo.git

# Later, if you need more history:
git fetch --unshallow`,

      right: `# Full clone every time
git clone \
  https://github.com/org/large-repo.git

# This downloads all branches,
# all tags, and full history
# (~2 GB for large repos)`,
    },

    correctSide: "left",
    explanationCorrect:
      "Shallow clones (`--depth 1`) download only the latest commit, and `--single-branch` skips all other branches. For CI pipelines that only need to build the current code, this can reduce clone times from minutes to seconds. You can always fetch more history later if needed with `--unshallow`.",
    explanationWrong:
      "A full clone downloads the entire history of every branch and tag. For repositories with years of history or large binary files, this can mean gigabytes of data. CI jobs rarely need the full history, so a full clone wastes bandwidth, disk space, and time on every pipeline run.",
    sourceUrl:
      "https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt",
    sourceLabel: "Git Docs: git clone --depth",
  },
  {
    id: "lf-006",
    category: "large-files",
    difficulty: "hard",
    title: "Large file commit enforcement",
    prompt:
      "Which pre-commit hook approach prevents large files from entering the repo?",
    content: {
      type: "code",
      lang: "bash",

      left: `# .husky/pre-commit
#!/bin/sh

# Check for files larger than 5 MB
MAX_SIZE=5242880
LARGE_FILES=$(git diff --cached \
  --name-only --diff-filter=d | \
  while read f; do
    size=$(wc -c < "$f" 2>/dev/null)
    if [ "$size" -gt $MAX_SIZE ]; then
      echo "  $f ($(($size/1048576)) MB)"
    fi
  done)

if [ -n "$LARGE_FILES" ]; then
  echo "Blocked: files over 5 MB:"
  echo "$LARGE_FILES"
  echo "Use Git LFS for large files."
  exit 1
fi`,

      right: `# No pre-commit hook
# Just tell developers in the README:
#
# "Please don't commit files
#  larger than 5 MB. Use Git LFS
#  for binary files."
#
# Trust the team to remember.`,
    },

    correctSide: "left",
    explanationCorrect:
      "A pre-commit hook that checks file sizes provides automated enforcement. Developers cannot accidentally commit large files, even in a hurry. Combined with Git LFS tracking in .gitattributes, this creates two layers of protection against repo bloat.",
    explanationWrong:
      "Relying on documentation and developer discipline does not scale. In a moment of urgency, anyone can forget to check file sizes. Once a large file enters Git history, it is permanent unless you rewrite history. Automated checks catch mistakes before they become permanent problems.",
    sourceUrl: "https://typicode.github.io/husky/",
    sourceLabel: "Husky: Git hooks made easy",
  },
  {
    id: "lf-007",
    category: "large-files",
    difficulty: "easy",
    title: "Large file storage approach",
    prompt: "Which approach handles large files better?",
    content: {
      type: "visual",
      left: { componentId: "FileTreeBloatedRepo" },
      right: { componentId: "FileTreeLFSRepo" },
    },
    correctSide: "right",
    explanationCorrect:
      "Git LFS stores large binary files on a separate server and replaces them with lightweight pointer files in the repository. This keeps clone times fast, reduces disk usage, and prevents the repository from growing uncontrollably as binary assets are updated over time.",
    explanationWrong:
      "Committing large binary files directly into Git stores every version in the repository history permanently. A 100 MB file that changes 10 times adds nearly 1 GB to the repo. Every clone downloads this full history, making onboarding slow and wasting bandwidth for the entire team.",
    sourceUrl: "https://git-lfs.com/",
    sourceLabel: "Git LFS: Large File Storage",
  },
];
